### ISSUE TITLE
wkhtmltopdf-binary-edge doesn't work on Alpine Linux

### ISSUE THREAD

**Issue by rmorlok** [pallymore/wkhtmltopdf-binary-edge#12]
`wkhtmltopdf-binary-edge` doesn't seem to have a binary that works with Alpine Linux.

Example Dockerfile:

```
FROM ruby:2.3-alpine

RUN gem install wkhtmltopdf-binary-edge
RUN wkhtmltopdf
```

Output:
```
Sending build context to Docker daemon  129.3MB
Step 1/3 : FROM ruby:2.3-alpine
 ---> ea8ea1068e3a
Step 2/3 : RUN gem install wkhtmltopdf-binary-edge
 ---> Using cache
 ---> 03c142572f4a
Step 3/3 : RUN wkhtmltopdf
 ---> Running in dc025755832d
/usr/local/bundle/gems/wkhtmltopdf-binary-edge-0.12.4.0/bin/wkhtmltopdf:17:in `exec': No such file or directory - /usr/local/bundle/gems/wkhtmltopdf-binary-edge-0.12.4.0/libexec/wkhtmltopdf-linux-amd64 (Errno::ENOENT)
	from /usr/local/bundle/gems/wkhtmltopdf-binary-edge-0.12.4.0/bin/wkhtmltopdf:17:in `<top (required)>'
	from /usr/local/bundle/bin/wkhtmltopdf:23:in `load'
	from /usr/local/bundle/bin/wkhtmltopdf:23:in `<main>'
```

This works with Debian. Example Dockerfile:

```
FROM ruby:2.3-stretch

RUN gem install wkhtmltopdf-binary-edge
RUN wkhtmltopdf
```

Output:

```
Sending build context to Docker daemon  129.3MB
Step 1/3 : FROM ruby:2.3-stretch
 ---> d91b0b9d80c1
Step 2/3 : RUN gem install wkhtmltopdf-binary-edge
 ---> Running in 698ae6f7ee4d
Successfully installed wkhtmltopdf-binary-edge-0.12.4.0
1 gem installed
Removing intermediate container 698ae6f7ee4d
 ---> 607d23d75b3c
Step 3/3 : RUN wkhtmltopdf
 ---> Running in ad3032567dcf
You need to specify at least one input file, and exactly one output file
Use - for stdin or stdout

Name:
  wkhtmltopdf 0.12.4 (with patched qt)

Synopsis:
  wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>

Document objects:
  wkhtmltopdf is able to put several objects into the output file, an object is
  either a single webpage, a cover webpage or a table of content.  The objects
...
```

The [Alpine `wkhtmltopdf` package](https://pkgs.alpinelinux.org/package/edge/testing/x86/wkhtmltopdf) is not qt-patched. There is a [qt-patch `wkhtmltopdf` for alpine docker image](https://github.com/madnight/docker-alpine-wkhtmltopdf), though.

**Comment by pallymore** [comment]
sorry for the super delayed response. 

yea the binary is not built for Alpine. 
You could build one from source by following the guides in https://github.com/wkhtmltopdf/wkhtmltopdf 

This repo is meant for common development uses (e.g. mac, ubuntu) - if I include a binary for every system then gem would be massive...

**Comment by rmorlok** [comment]
Fair point, but Alpine is becoming much more common in Dockerized environments.

**Comment by pallymore** [comment]
To be honest I'm doing away with the gem method in my newer projects, especially when using Docker.  Personally I don't think we should be using a gem in order to add an external dependency (especially when that dependency highly relies on the operating system). It's probably much more elegant to dynamically pull & install the necessary binaries in your docker environments :)
