### ISSUE TITLE
update to 0.12.5

### ISSUE THREAD

**Issue by deneuxa** [pallymore/wkhtmltopdf-binary-edge#13]
0.12.5 is out :)
https://wkhtmltopdf.org/downloads.html

Is it possible to update the gem to this version ?

It solves a lot of issues with Mac OS :)

thanks !

**Comment by dkrosso** [comment]
+1

**Comment by pallymore** [comment]
Uhh sorry, somehow I missed this one. 
Working on this right now

**Comment by deneuxa** [comment]
thanks !

2018-06-23 9:21 GMT+04:00 Yurui Zhang <notifications@github.com>:
