### ISSUE TITLE
Can't update gem version.

### ISSUE THREAD

**Issue by NinjaValerok** [pallymore/wkhtmltopdf-binary-edge#14]
Hi, i try to update gem, but I have an error: 
Could not find gem 'wkhtmltopdf-binary-edge (~> 0.12.5.0)' in any of the gem sources listed in your Gemfile.

My source is http://rubygems.org. On rubygems last version is 0.12.5.0.pre.alpha0, but on this version i have an error ' /bundle/gems/wkhtmltopdf-binary-edge-0.12.5.0.pre.alpha0/libexec/wkhtmltopdf-linux-amd64: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory'

When i write
gem 'wkhtmltopdf-binary-edge', git: 'https://github.com/pallymore/wkhtmltopdf-binary-edge.git'
and run bundle nothing happened, just fetching.

**Comment by pallymore** [comment]
i'm looking into it.

**Comment by pallymore** [comment]
Howdy, I tested this in macOS and Heroku-16 and bumped the version of the gem so it should be working now. 

the test app is hosted here: https://wktest-pally.herokuapp.com/ 

you might want to do `bundle install --full-index` if it still not showing up for you. 

in terms of the missing libraries error - what OS you are running? This gem right now only works with macOS and Ubuntu 16 (heroku-16 stack).

**Comment by NinjaValerok** [comment]
Hi! Thank you! Today i can update, just run bundle.
