### ISSUE TITLE
Wktohtmltopdf-binary-edge not working in heroku

### ISSUE THREAD

**Issue by Ajithtechkumar** [pallymore/wkhtmltopdf-binary-edge#21]
First of all I tried it with wktmltopdf-heroku gem it didn't work then i continued to use this gem with heroku 18 but it showed the below error:
![Screenshot from 2020-04-08 19-12-51](https://user-images.githubusercontent.com/61178885/78812183-a2dd3100-79e8-11ea-8bdf-50f4a3c08c10.png)

From the error it seems that i need to install the libpng12 package in heroku 18 since it doesn't have support for that. 
Can anyone help me with this ...

Also I made this gem to make my charts works in development and I am afraid I can't choose any other gems.

**Comment by bylaxdee** [comment]
https://razorjack.net/wkhtmltopdf-on-heroku-evaluating-different-installation-options/ 
this article should help you, this gem is for local only.

**Comment by Ajithtechkumar** [comment]
@geekdeepak well i already tried those methods. In heroku i solved the issue my downgrading to heroku stack 16, What i didn't understand is why the libpng12 package is not supported in heroku 18

**Comment by DemitryT** [comment]
Make sure to have libssl in Aptfile and try using this gem in the production block: `gem 'wkhtmltopdf-heroku', '2.12.5.0'`

**Comment by pallymore** [comment]
Please use `wkhtmltopdf-heroku`https://github.com/rposborne/wkhtmltopdf-heroku  instead - this gem is for local development only
