### ISSUE TITLE
Command Error: The `wkhtmltopdf` executable in the `wkhtmltopdf-binary-edge` gem is being loaded, but it's also present in other gems (wkhtmltopdf-binary)

### ISSUE THREAD

**Issue by RubenGram** [pallymore/wkhtmltopdf-binary-edge#22]
## Issue description

The next problem ocurred when I was trying to create a pdf:
"_The `wkhtmltopdf` executable in the `wkhtmltopdf-binary-edge` gem is being loaded, but it's also present in other gems (wkhtmltopdf-binary) If you meant to run the executable for another gem, make sure you use a project specific binstub (`bundle binstub <gem_name>`)_"

Are both wkhtmltopdf-binary-edge and wkhtmltopdf-binary gems necessary? 

`Error: Failed to execute: ["/.rbenv/versions/2.3.6/bin/wkhtmltopdf", "-q", "--encoding", "UTF-8", "file:///var/folders/ds/70lrh2194yb9jnwgzx28vm100000gn/T/wicked_pdf20200423-33047-47tsw2.html", "/var/folders/ds/70lrh2194yb9jnwgzx28vm100000gn/T/wicked_pdf_generated_file20200423-33047-1hbwcmu.pdf"] Error: PDF could not be generated! Command Error: The `wkhtmltopdf` executable in the `wkhtmltopdf-binary-edge` gem is being loaded, but it's also present in other gems (wkhtmltopdf-binary). If you meant to run the executable for another gem, make sure you use a project specific binstub (`bundle binstub <gem_name>`). If you plan to use multiple conflicting executables, generate binstubs for them and disambiguate their names. /.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/wkhtmltopdf-binary-edge-0.12.2.1/bin/wkhtmltopdf:17:in `exec': Bad CPU type in executable - /.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/wkhtmltopdf-binary-edge-0.12.2.1/libexec/wkhtmltopdf-darwin-x86 (Errno::E086) from /.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/wkhtmltopdf-binary-edge-0.12.2.1/bin/wkhtmltopd`

## System specifications

wicked_pdf gem version: **0.11.0**

wkhtmltopdf version (output of `wkhtmltopdf --version`): **0.12.5 (with patched qt)**

wkhtmltopdf-binary version: **0.12.4**

wkhtmltopdf-binary-edge version: **0.12.2.1**

platform/distribution and version: **MacOS Catalina**

Rails version: **4.2.1**

**Comment by promisepreston** [comment]
Hi encountered this same issue.

Remove the `wkhtmltopdf-binary-edge` from your `Gemfile` it has conflicting executables with the `wkhtmltopdf-binary`

You can see the solution here: https://stackoverflow.com/a/61815636/10907864

**Comment by pallymore** [comment]
Hi - please only use one of `wkhtmltopdf-binary` & this gem.
