### ISSUE TITLE
Add composer file

### ISSUE THREAD

**Issue by mdeboer** [pallymore/wkhtmltopdf-binary-edge#8]
Please add a composer file and submit it to packagegist. Aside from the ruby stuff, the binaries don't require ruby and are perfectly usable. There are other wkhtmltopdf composer packages out there but they are either outdated or don't include the darwin binary.

Having one package that includes them all would be great for CI, despite the size.

**Comment by pallymore** [comment]
Hello, 
Yea, this is just a simple ruby wrapper for wkhtmltodpf binary and some quick configurations for 3 of the most popular (as of today) html to pdf ruby gems. 
If you are interested in making a PHP version, you can download appropriate wkhtmltopdf binaries here: https://github.com/wkhtmltopdf/wkhtmltopdf

Thanks,
P
